version: '2'

services:
  postgres:
    image: postgres:9.6
    environment:
     - POSTGRES_DB=test
     - POSTGRES_USER=test 
     - POSTGRES_PASSWORD=test
     
  pgbouncer:
    image: gcavalcante8808/pgbouncer
    build: .
    environment:
      DB_HOST: postgres
      DB_NAME: test
      DB_USER: test
      DB_PASSWORD: test
      CONNECTION_OPTIONS: client_encoding='UTF8'
      IGNORE_STARTUP_OPTIONS: options

