version: '2'

services:
  postgres:
    image: postgres:9.6
    environment:
     - POSTGRES_DB=test
     - POSTGRES_USER=test 
     - POSTGRES_PASSWORD=test
     
  pgbouncer:
    image: gcavalcante8808/pgbouncer
    environment:
     - DB_HOST=postgres
     - DB_NAME=test
     - DB_USER=test
     - DB_PASSWORD=test

